### PR TITLE
Add support for multi dim arrays

### PR DESCRIPTION
**Pull request by ddijk**
Now that Enunciate supports multi dimensional arrays, like int[][], this changes adds this to the module. Note that you have to use @TypeHint(int[][].class) on the field's getter in order to get the correct type in the HTML of Enunciate. For the Jyske module @TypeHint is not needed.

### CODE REVIEW

**Comment by jskovjyskebankdk** [comment]
Thanks, I have merged the changes.

**Comment by ddijk** [comment]
Hi Jesper,

I have finished all the changes that I needed, for now. Can you make a 
release and push it Maven Central, because currently I am depending on 
1.0.9-SNAPSHOT?

Kind regards,
Dick
Jesper Skov schreef op 2019-09-09 08:46:

**Comment by jskovjyskebankdk** [comment]
Done, 1.1.2 is on Central. Search index not updated yet, but it is there.

**Comment by ddijk** [comment]
Thanks!
Dick
Jesper Skov schreef op 2019-09-09 09:47:

**Pull request closed without merging**
