### PR TITLE
#32 Added support for namespace prefix.

### PR DESCRIPTION
**Pull request by mengjiann**

### CODE REVIEW

**Comment by jskovjyskebankdk** [comment]
Thanks for this.
I would like you to add an end-to-end test, that demonstrates use of the feature with input and expected output.
Similar to what was added in https://github.com/Jyskebank/enunciate-openapi/commit/65ba14795010dc93ebc177315db6d44a93b27c17

**Comment by mengjiann** [comment]
sure. let me add that.

**Comment by mengjiann** [comment]
Please verify. Thanks!

**Comment by jskovjyskebankdk** [comment]
I will, maybe later this week. Thanks!

**Comment by jskovjyskebankdk** [comment]
Super. Thanks!

**Pull request merged**
